---


  - name: Install PPAs
    apt_repository: repo={{item}} update_cache=yes
    with_items:
      - ppa:wireshark-dev/stable

  - name: Install Packages
    apt: name={{item}}
    with_items:
      - wireshark-qt
